from enum import Enum
import pygame
from main import TILE_SIZE


class posToCoord(Enum):
    A8 = pygame.Vector2(0 * TILE_SIZE, 0 * TILE_SIZE)
    A7 = pygame.Vector2(0 * TILE_SIZE, 1 * TILE_SIZE)
    A6 = pygame.Vector2(0 * TILE_SIZE, 2 * TILE_SIZE)
    A5 = pygame.Vector2(0 * TILE_SIZE, 3 * TILE_SIZE)
    A4 = pygame.Vector2(0 * TILE_SIZE, 4 * TILE_SIZE)
    A3 = pygame.Vector2(0 * TILE_SIZE, 5 * TILE_SIZE)
    A2 = pygame.Vector2(0 * TILE_SIZE, 6 * TILE_SIZE)
    A1 = pygame.Vector2(0 * TILE_SIZE, 7 * TILE_SIZE)

    B8 = pygame.Vector2(1 * TILE_SIZE, 0 * TILE_SIZE)
    B7 = pygame.Vector2(1 * TILE_SIZE, 1 * TILE_SIZE)
    B6 = pygame.Vector2(1 * TILE_SIZE, 2 * TILE_SIZE)
    B5 = pygame.Vector2(1 * TILE_SIZE, 3 * TILE_SIZE)
    B4 = pygame.Vector2(1 * TILE_SIZE, 4 * TILE_SIZE)
    B3 = pygame.Vector2(1 * TILE_SIZE, 5 * TILE_SIZE)
    B2 = pygame.Vector2(1 * TILE_SIZE, 6 * TILE_SIZE)
    B1 = pygame.Vector2(1 * TILE_SIZE, 7 * TILE_SIZE)

    C8 = pygame.Vector2(2 * TILE_SIZE, 0 * TILE_SIZE)
    C7 = pygame.Vector2(2 * TILE_SIZE, 1 * TILE_SIZE)
    C6 = pygame.Vector2(2 * TILE_SIZE, 2 * TILE_SIZE)
    C5 = pygame.Vector2(2 * TILE_SIZE, 3 * TILE_SIZE)
    C4 = pygame.Vector2(2 * TILE_SIZE, 4 * TILE_SIZE)
    C3 = pygame.Vector2(2 * TILE_SIZE, 5 * TILE_SIZE)
    C2 = pygame.Vector2(2 * TILE_SIZE, 6 * TILE_SIZE)
    C1 = pygame.Vector2(2 * TILE_SIZE, 7 * TILE_SIZE)

    D8 = pygame.Vector2(3 * TILE_SIZE, 0 * TILE_SIZE)
    D7 = pygame.Vector2(3 * TILE_SIZE, 1 * TILE_SIZE)
    D6 = pygame.Vector2(3 * TILE_SIZE, 2 * TILE_SIZE)
    D5 = pygame.Vector2(3 * TILE_SIZE, 3 * TILE_SIZE)
    D4 = pygame.Vector2(3 * TILE_SIZE, 4 * TILE_SIZE)
    D3 = pygame.Vector2(3 * TILE_SIZE, 5 * TILE_SIZE)
    D2 = pygame.Vector2(3 * TILE_SIZE, 6 * TILE_SIZE)
    D1 = pygame.Vector2(3 * TILE_SIZE, 7 * TILE_SIZE)

    E8 = pygame.Vector2(4 * TILE_SIZE, 0 * TILE_SIZE)
    E7 = pygame.Vector2(4 * TILE_SIZE, 1 * TILE_SIZE)
    E6 = pygame.Vector2(4 * TILE_SIZE, 2 * TILE_SIZE)
    E5 = pygame.Vector2(4 * TILE_SIZE, 3 * TILE_SIZE)
    E4 = pygame.Vector2(4 * TILE_SIZE, 4 * TILE_SIZE)
    E3 = pygame.Vector2(4 * TILE_SIZE, 5 * TILE_SIZE)
    E2 = pygame.Vector2(4 * TILE_SIZE, 6 * TILE_SIZE)
    E1 = pygame.Vector2(4 * TILE_SIZE, 7 * TILE_SIZE)

    F8 = pygame.Vector2(5 * TILE_SIZE, 0 * TILE_SIZE)
    F7 = pygame.Vector2(5 * TILE_SIZE, 1 * TILE_SIZE)
    F6 = pygame.Vector2(5 * TILE_SIZE, 2 * TILE_SIZE)
    F5 = pygame.Vector2(5 * TILE_SIZE, 3 * TILE_SIZE)
    F4 = pygame.Vector2(5 * TILE_SIZE, 4 * TILE_SIZE)
    F3 = pygame.Vector2(5 * TILE_SIZE, 5 * TILE_SIZE)
    F2 = pygame.Vector2(5 * TILE_SIZE, 6 * TILE_SIZE)
    F1 = pygame.Vector2(5 * TILE_SIZE, 7 * TILE_SIZE)

    G8 = pygame.Vector2(6 * TILE_SIZE, 0 * TILE_SIZE)
    G7 = pygame.Vector2(6 * TILE_SIZE, 1 * TILE_SIZE)
    G6 = pygame.Vector2(6 * TILE_SIZE, 2 * TILE_SIZE)
    G5 = pygame.Vector2(6 * TILE_SIZE, 3 * TILE_SIZE)
    G4 = pygame.Vector2(6 * TILE_SIZE, 4 * TILE_SIZE)
    G3 = pygame.Vector2(6 * TILE_SIZE, 5 * TILE_SIZE)
    G2 = pygame.Vector2(6 * TILE_SIZE, 6 * TILE_SIZE)
    G1 = pygame.Vector2(6 * TILE_SIZE, 7 * TILE_SIZE)

    H8 = pygame.Vector2(7 * TILE_SIZE, 0 * TILE_SIZE)
    H7 = pygame.Vector2(7 * TILE_SIZE, 1 * TILE_SIZE)
    H6 = pygame.Vector2(7 * TILE_SIZE, 2 * TILE_SIZE)
    H5 = pygame.Vector2(7 * TILE_SIZE, 3 * TILE_SIZE)
    H4 = pygame.Vector2(7 * TILE_SIZE, 4 * TILE_SIZE)
    H3 = pygame.Vector2(7 * TILE_SIZE, 5 * TILE_SIZE)
    H2 = pygame.Vector2(7 * TILE_SIZE, 6 * TILE_SIZE)
    H1 = pygame.Vector2(7 * TILE_SIZE, 7 * TILE_SIZE)